name: Feature Request
description: Suggest something new or an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We read every feature request. The best ones describe a **problem** first and a solution second — sometimes the right solution is different from what you'd expect.

  - type: dropdown
    id: area
    attributes:
      label: What area does this relate to?
      options:
        - Dictation (system-wide voice input)
        - File transcription
        - YouTube transcription
        - Text processing and vocabulary
        - Export formats
        - UI and design
        - Performance
        - Accessibility
        - Something else
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the frustration, limitation, or gap.
      placeholder: |
        When I'm dictating long passages, I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal outcome. Be as specific as you want.
      placeholder: |
        It would be great if MacParakeet could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Workarounds or alternatives you've tried
      description: Have you found any way around this?

  - type: dropdown
    id: importance
    attributes:
      label: How much does this matter to you?
      options:
        - Nice to have — would be a pleasant surprise
        - Important — noticeably improves my workflow
        - Critical — I need this to keep using the app
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched [existing issues](https://github.com/moona3k/macparakeet-community/issues) for duplicates
          required: true
        - label: I'd be willing to test a beta of this feature
